rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head

env:
  - "TEST_SUITE=javascript"
  - "TEST_SUITE=rspec"

matrix:
  allow_failures:
    - rvm: ruby-head

addons:
  postgresql: 9.3

script: bin/ci

before_script:
  - cp config/travis.database.yml config/database.yml
  - psql -c "create database ruby_bench_test;" -U postgres
