rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

addons:
  postgresql: 9.3

script:
  - RAILS_ENV=test xvfb-run bundle exec rake --trace db:migrate spec

before_script:
  - cp config/travis.database.yml config/database.yml
  - psql -c "create database ruby_bench_test;" -U postgres
