rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

addons:
  postgresql: 9.3

before_script:
  - cp config/travis.database.yml config/database.yml
  - 'RAILS_ENV=test xvfb-run bundle exec rake db:create db:schema:load --trace'
