default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ruby_bench
  password:

development:
  <<: *default
  database: ruby_bench_development

test:
  <<: *default
  database: ruby_bench_test

production:
  <<: *default
  database: ruby_bench_production
